#include "stm32l4xx_hal.h"

//garden pump scheduled duinrg 9AM, 5PM and 1AM.
#define GARDEN_PUMP_SCHED_HOUR_1 9 
#define GARDEN_PUMP_SCHED_MIN_1 0
#define GARDEN_PUMP_SCHED_HOUR_2 17
#define GARDEN_PUMP_SCHED_MIN_2 0
#define GARDEN_PUMP_SCHED_HOUR_3 1 
#define GARDEN_PUMP_SCHED_MIN_3 0

#define AQUA_WATER_TOWER_MIN_1 15
#define AQUA_WATER_TOWER_MIN_2 45
#define AQUA_CHECK_FISH_FOOD_HOUR 6
#define AQUA_CHECK_FISH_FOOD_MIN 0
#define AQUA_CHECK_FISH_TANK_LVL_MIN 0

#define AQUA_FEED_FISH_HOUR_1 9
#define AQUA_FEED_FISH_MIN_1 0
#define AQUA_FEED_FISH_HOUR_2 17
#define AQUA_FEED_FISH_MIN_2 0
#define AQUA_FEED_FISH_HOUR_3 1
#define AQUA_FEED_FISH_MIN_3 0
